"use client";

import { Card, StatusBadge } from "@/components/ui";
import { SAFETY_LABELS, SAFETY_EXPLAIN, StructuredAnswer, Citation } from "@/lib/ai-engine";
import type { StatusType } from "@/components/ui/StatusBadge";

const SAFETY_TO_STATUS: Record<string, StatusType> = {
  safe_information: "safe",
  needs_clinician_review: "review",
  urgent_medical_attention: "urgent",
  insufficient_information: "pending",
  disallowed_medical_advice: "urgent",
};

/**
 * StructuredAIResponse renderer — never a chat bubble.
 * Every AI answer renders as:
 *   Summary → Key Findings → Sources → Missing Info → Safety Status
 */
export default function StructuredResponse({
  answer,
  compact = false,
}: {
  answer: StructuredAnswer;
  compact?: boolean;
}) {
  const status = SAFETY_TO_STATUS[answer.safety] ?? "pending";

  return (
    <div className="space-y-4">
      <Card>
        <h2 className="text-lg font-heading text-ink-primary mb-3">Summary</h2>
        <p className="text-sm text-ink-primary leading-relaxed whitespace-pre-wrap">
          {answer.summary}
        </p>
      </Card>

      {answer.key_findings.length > 0 && (
        <Card>
          <h2 className="text-lg font-heading text-ink-primary mb-3">Key findings</h2>
          <ul className="space-y-2">
            {answer.key_findings.map((f, i) => (
              <li key={i} className="border-l-2 border-brand-teal pl-3 text-sm text-ink-primary">
                {f}
              </li>
            ))}
          </ul>
        </Card>
      )}

      {answer.plain_terms && answer.plain_terms.length > 0 && (
        <Card>
          <h2 className="text-lg font-heading text-ink-primary mb-1">
            In plain language
          </h2>
          <p className="text-xs text-ink-secondary mb-3">
            Medical terms from this answer, explained for readers without a
            medical background.
          </p>
          <ul className="space-y-3">
            {answer.plain_terms.map((t, i) => (
              <li key={i} className="text-sm border-l-2 border-clinical-border pl-3">
                <p className="font-medium text-ink-primary">{t.term}.</p>
                <p className="text-ink-secondary mt-0.5">
                  <span className="text-xs font-semibold text-ink-secondary uppercase tracking-wider mr-1">
                    Explain:
                  </span>
                  {t.meaning}
                </p>
              </li>
            ))}
          </ul>
        </Card>
      )}

      {answer.citations.length > 0 && (
        <Card>
          <h2 className="text-lg font-heading text-ink-primary mb-3">Sources</h2>
          <ul className="space-y-3">
            {answer.citations.map((c: Citation, i: number) => (
              <li key={i} className="text-sm">
                <p className="text-xs text-ink-secondary">
                  ↳ <span className="font-medium text-ink-primary">{c.document_title}</span>
                  {` — ${c.section}`}
                </p>
                <p className="text-xs text-ink-secondary mt-0.5 italic">
                  &ldquo;{c.snippet}&rdquo;
                </p>
              </li>
            ))}
          </ul>
        </Card>
      )}

      {answer.missing_info.length > 0 && (
        <Card>
          <h2 className="text-lg font-heading text-ink-primary mb-3">Missing info</h2>
          <p className="text-xs text-ink-secondary uppercase tracking-wider mb-2">
            What this answer does not know
          </p>
          <ul className="list-disc list-inside space-y-1 text-sm text-ink-secondary">
            {answer.missing_info.map((m, i) => (
              <li key={i}>{m}</li>
            ))}
          </ul>
        </Card>
      )}

      <div className="space-y-2">
        <div className="flex items-center justify-between flex-wrap gap-2">
          <StatusBadge
            status={status}
            label={`Safety: ${SAFETY_LABELS[answer.safety]}`}
            dot
          />
          <span className="text-xs text-ink-secondary">
            Generated by: {answer.generator === "backend-rag" ? "RAG pipeline" : "template engine (prototype)"}
          </span>
        </div>
        {!compact && (
          <p className="text-xs text-ink-secondary">{answer.safety_note}</p>
        )}
      </div>
    </div>
  );
}
